#version 430
precision mediump float;

layout (local_size_x = 10, local_size_y = 10) in;

layout (rgba32f, binding = 0) uniform image2D a_positions;
layout (rgba32f, binding = 1) uniform image2D a_speeds;

layout (location = 2) uniform float u_step;

void main()
{
	ivec2 coords = ivec2(gl_GlobalInvocationID);
	vec3 position = imageLoad(a_positions, coords).rgb;
	vec3 speed = imageLoad(a_speeds, coords).rgb;

	imageStore(a_positions, coords, vec4(position + (speed * u_step), 1.));
}
